### ISSUE TITLE
Usar la branch gh-pages

### ISSUE THREAD

**Issue by iblancasa** [RDCH106/GitHubRankingsSpain-viewer#2]
En vez de utilizar la dirección de los ficheros en "raw" (https://rawgit.com/RDCH106/ghrankings-viewer/master/ghrankings-viewer.html) mueve el código de producción a la branch `gh-pages`. Es una buena práctica y te aseguras tener una URL más bonita.

**Comment by RDCH106** [comment]
Totalmente cierto!!
La URL se acorta considerablemente, de momento tiraba de los ficheros raw, por el tema de que estaba realizando muchos cambios y al final desplegar los cambios en la rama es un paso más... de esfuerzo despreciable pero repetitivo.

Ahora que está más estable el desarrollo, es posible el plantemaiento que dices de volcarlo en un gh-pages. Suelo usar las gh-pages cuando ya empiezo a trabajar con entornos de desarrollo y producción (ramas develop y master). A veces ni eso, por el tema de que no espero ofrecerlo publicamente y me interesa solamente que los desarrolladores puedan probar las cosas en caliente.

Cuando tenga un rato lo monto desde un branch gh-pages.
