### ISSUE TITLE
Bug: las filas no se ordenan bien en la tabla

### ISSUE THREAD

**Issue by iblancasa** [RDCH106/GitHubRankingsSpain-viewer#3]
Cuando ordenas las filas por una columna que no es el número de contribuciones, el resultado no es muy bueno. Ejemplo: número de contribuciones privadas.
![screen](https://user-images.githubusercontent.com/4806311/31402911-c1e906a6-adf7-11e7-9e3d-42393f0be9a5.jpg)

**Comment by RDCH106** [comment]
Yo lo veo bien, esta ordenado según contribuciones públicas y no privadas.

Fíjate que el icono de ordenación está detrás de cada nombre de la columna. Has dado a ordenar por Contribuciones públicas, pensando que lo hacías para Contribuciones privadas.

**Comment by iblancasa** [comment]
Verás que está marcado más oscuro contribuciones privadas. Está ordenado de mayor a menor número de contribuciones privadas, creo. Si no, que el icono sea más oscuro es muy confuso.
Además también se puede "ordenar por avatar" (aunque no cambia el orden de las filas, según el icono, sí xD)

**Comment by RDCH106** [comment]
Intento reproducir el problema de ordenación para cualquier campo que no sea el de avatar y funciona perfectamente:

![imagen](https://user-images.githubusercontent.com/1483414/31414134-c1b8c70a-ae1c-11e7-9fb6-7b3c16edd25c.png)

La ordenación que dices que está más oscura es la de Contribuciones públicas, fíjate que que el icono de ordenación se encuetra a la derecha de cada cabecera de columna (ver imagen de ordenación por Contribuciones privadas). Es cierto que a lo mejor debería quedar más pegado a la cabecera de columna, para no confundir con la ordenación de la columna contigua. Me lo anoto como punto de mejora, pero las ordenaciones son correctas.

Lo de ordenar por el avartar es cierto que no tiene sentido, es otro punto de mejora. En cualquier caso no funciona.... 😅

Gracias por las apreciaciones y espero corregirlo en futuras revisiones.

**Comment by RDCH106** [comment]
He cambiado la posición del icono de ordenación para que se vea bien qué icono corresponde a qué columna:

![imagen](https://user-images.githubusercontent.com/1483414/31431785-f44bc5c0-ae74-11e7-9834-3cd2a2014794.png)

@iblancasa así lo ves mejor?

**Comment by RDCH106** [comment]
Ya no se muestra el icono de ordenación en la columna de Avatar:

![imagen](https://user-images.githubusercontent.com/1483414/31433232-f97bc2ee-ae78-11e7-9d78-27fab10ced4e.png)
